spring:
  kafka:
    consumer:
      # @see org/springframework/boot/autoconfigure/kafka/KafkaAutoConfiguration.java#kafkaConsumerFactory
      # @see org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#buildCommonProperties
      bootstrap-servers:
        - localhost:9092
        - localhost:9093
        - localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: order-notification-events-group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafka-spring-sample?createDatabaseIfNotExist=true
    username: root
    password: 1qazxsw2
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
